### **NUMPY: Arrays and Matrices**

**NumPy** is an extension to the Python programming language, adding support for large, multi-dimensional (numerical) arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays. NumPy is having the full form **"Numeric Python"**.

In [1]:
# Importing Required module
import numpy as np

### **Create arrays**

In [3]:
# create ndarrays from lists
# note: every element must be the same data type (will be converted is possible)
data1 = [1, 2, 3, 4, 5]        # list (all are interger data)
arr1 = np.array(data1)         # 1-D array
print (data1, type(data1), arr1, type(arr1))
data1 = [1, 2.5, 3, 4, 5]      # list (mixed data types)
arr1 = np.array(data1)         # 1-D array (converted to all float data)
print (data1, type(data1), arr1, type(arr1))

[1, 2, 3, 4, 5] <class 'list'> [1 2 3 4 5] <class 'numpy.ndarray'>
[1, 2.5, 3, 4, 5] <class 'list'> [1.  2.5 3.  4.  5. ] <class 'numpy.ndarray'>


In [5]:
print (list(range(1, 5)))             # range function creates a list
data2 = [range(1, 5), range(5, 9)]    # list of lists
arr2 = np.array(data2)                # 2-D array
print (data2, list(data2), type(data2))
print (arr2, type(arr2))
for x in np.nditer(arr2):             # iterating over the ndarray
    print (x, end = ", ")

[1, 2, 3, 4]
[range(1, 5), range(5, 9)] [range(1, 5), range(5, 9)] <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>
1, 2, 3, 4, 5, 6, 7, 8, 

In [7]:
list2 = arr2.tolist()                  # converting ndarray back to a list
print (list2, type(list2))
list2 = list(arr2)                  # converting ndarray back to a list
print (list2, type(list2))

[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>
[array([1, 2, 3, 4]), array([5, 6, 7, 8])] <class 'list'>


In [8]:
# examining arrays
print (arr1, type(arr1), id(arr1))
print (arr2, type(arr2), id(arr2))
print (arr1.dtype, arr2.dtype)         # data type of the array
print (arr1.shape, type(arr1.shape))   # shape of the array (5,) => Singleton notation
print (arr2.shape, type(arr2.shape))   # shape of the array (2, 4)
print (arr1.ndim, arr2.ndim)           # number of dimensions
print (arr1.size, arr2.size)           # total number of elements
print (len(arr1), len(arr2))           # size of the first dimension (aka axis)

[1.  2.5 3.  4.  5. ] <class 'numpy.ndarray'> 2887413441488
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> 2887413436112
float64 int32
(5,) <class 'tuple'>
(2, 4) <class 'tuple'>
1 2
5 8
5 2


In [9]:
# create special arrays
print (np.zeros(10))
print (np.zeros(10, dtype = np.int8))
print (np.zeros(10).astype(int))
print (np.zeros((3, 6)))
print (np.zeros((3, 6), int))
print (np.zeros((3, 6)).astype(int))
print (np.ones(10))
print (np.ones((3, 6)))
print (np.linspace(0, 1, 5))  # 0 to 1 (inclusive) with 5 points
print (np.logspace(0, 3, 4))  # 10^0 to 10^3 (inclusive) with 4 points

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[0.   0.25 0.5  0.75 1.  ]
[   1.   10.  100. 1000.]


In [10]:
# arange is like range, except it returns an array (but not a list)
int_list = list(range(5))
print (int_list, type(int_list[0]), type(int_list))
int_array = np.arange(5)
print (int_array, int_array.dtype, type(int_array))
float_array = int_array.astype(float)
print (float_array, float_array.dtype, type(float_array))

[0, 1, 2, 3, 4] <class 'int'> <class 'list'>
[0 1 2 3 4] int32 <class 'numpy.ndarray'>
[0. 1. 2. 3. 4.] float64 <class 'numpy.ndarray'>


### **Reshaping**

In [13]:
matrix = np.arange(10, dtype = float)
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = matrix.reshape((2, 5))
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = matrix.reshape((2, 5)).astype(int)
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = matrix.astype(int).reshape((2, 5))
print (matrix, matrix.dtype, type(matrix), matrix.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64 <class 'numpy.ndarray'> (10,)
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] float64 <class 'numpy.ndarray'> (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]] int32 <class 'numpy.ndarray'> (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]] int32 <class 'numpy.ndarray'> (2, 5)


In [17]:
# transpose of a matrix
matrix = np.arange(10, dtype = float)
matrix = matrix.astype(int).reshape((2, 5))
print (matrix)
matrix = matrix.T
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = matrix.flatten()
print (matrix, matrix.dtype, type(matrix), matrix.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]] int32 <class 'numpy.ndarray'> (5, 2)
[0 5 1 6 2 7 3 8 4 9] int32 <class 'numpy.ndarray'> (10,)


In [18]:
# transpose of a matrix
matrix = np.arange(10, dtype = float)
matrix = matrix.astype(int).reshape((2, 5))
print (matrix)
matrix = matrix.transpose()
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = matrix.flatten()
print (matrix, matrix.dtype, type(matrix), matrix.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]] int32 <class 'numpy.ndarray'> (5, 2)
[0 5 1 6 2 7 3 8 4 9] int32 <class 'numpy.ndarray'> (10,)


### **Append, Insert, Delete and Sort**

In [20]:
matrix = np.arange(10, dtype = np.int8)
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.append(matrix, [10, 11, 12])
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.insert(matrix, 3, [13, 14, 15])
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.delete(matrix, [5, 6, 7])
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.delete(matrix, range(5, 8))
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = np.sort(matrix)    # sort in the ascending order
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = -np.sort(-matrix)    # sort in the descending order
print (matrix, matrix.dtype, type(matrix), matrix.shape)

[0 1 2 3 4 5 6 7 8 9] int8 <class 'numpy.ndarray'> (10,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12] int32 <class 'numpy.ndarray'> (13,)
[ 0  1  2 13 14 15  3  4  5  6  7  8  9 10 11 12] int32 <class 'numpy.ndarray'> (16,)
[ 0  1  2 13 14  5  6  7  8  9 10 11 12] int32 <class 'numpy.ndarray'> (13,)
[ 0  1  2 13 14  8  9 10 11 12] int32 <class 'numpy.ndarray'> (10,)
[ 0  1  2  8  9 10 11 12 13 14] int32 <class 'numpy.ndarray'> (10,)
[14 13 12 11 10  9  8  2  1  0] int32 <class 'numpy.ndarray'> (10,)


### **Concatenation and Stack of 2 Arrays**

In [23]:
a=np.array([[1, 2], [3, 4]])
print ('First array:')
print (a)
print ('')

b = np.array([[5, 6], [7, 8]])
print ('Second array:')
print (b)
print ('')

# both the arrays are of same dimensions
print ('Joining the two arrays along axis 0:')
print (np.concatenate((a, b), axis=0))
print ('')

print ('Joining the two arrays along axis 1:')
print (np.concatenate((a, b), axis=1))

First array:
[[1 2]
 [3 4]]

Second array:
[[5 6]
 [7 8]]

Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [24]:
print ('Stack the two arrays along axis 0:')
print (np.stack((a, b), 0))
print ('\n')

print ('Stack the two arrays along axis 1:')
print (np.stack((a, b), 1))

Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stack the two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [27]:
matrix = np.array([[100, 200, 300, 400]])
print (matrix, type(matrix), matrix.ndim)
arr = matrix.reshape(-1)
print (arr, type(arr), arr.ndim)
arr = matrix.reshape(-1, 1, 4)
print (arr, type(arr), arr.ndim)
arr = matrix.reshape(1, 4, -1)
print (arr, type(arr), matrix.ndim)

[[100 200 300 400]] <class 'numpy.ndarray'> 2
[100 200 300 400] <class 'numpy.ndarray'> 1
[[[100 200 300 400]]] <class 'numpy.ndarray'> 3
[[[100]
  [200]
  [300]
  [400]]] <class 'numpy.ndarray'> 2


### **Selection**

In [28]:
data1 = [1, 2, 3, 4, 5]        # list
arr1 = np.array(data1)         # 1-D array
print (arr1, type(arr1), arr1.dtype, arr1.shape)
print (arr1[0], arr1[-5])      # 0-th element (indexing like a list)
print (arr1[4], arr1[-1])
print (arr1[2:], arr1[:3])
print (arr1[::-1])

[1 2 3 4 5] <class 'numpy.ndarray'> int32 (5,)
1 1
5 5
[3 4 5] [1 2 3]
[5 4 3 2 1]


### **Views and copies**

In [29]:
arr = np.arange(10)
print (arr, type(arr), arr.dtype, arr.shape)
print (arr[5:8])
arr[5:8] = 12       # all the pre-existing values at those index places will be over-written
print (arr)
arr_view = arr[5:8]   # creates a view of arr, not a copy
print (arr_view, type(arr_view), arr_view.dtype, arr_view.shape)
arr_view[:] = 13
print (arr_view)
print (arr)
arr_copy = arr[5:8].copy()   # creates a copy of arr
print (arr_copy, type(arr_copy), arr_copy.dtype, arr_copy.shape)
arr_copy[:] = 14
print (arr_copy)
print (arr)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int32 (10,)
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12] <class 'numpy.ndarray'> int32 (3,)
[13 13 13]
[ 0  1  2  3  4 13 13 13  8  9]
[13 13 13] <class 'numpy.ndarray'> int32 (3,)
[14 14 14]
[ 0  1  2  3  4 13 13 13  8  9]


### **Using Boolean Arrays**

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print (arr, arr > 5)
print (arr[arr > 5], arr[~(arr > 5)])  # ~ denotes not
print (arr % 2 == 0)
print (arr[arr % 2 == 0])
print (arr[(arr > 3) & (arr < 8)])
arr = np.arange(0, 61)
print (arr[(arr % 2 == 0) & (arr % 3 == 0)])

[1 2 3 4 5 6 7 8 9] [False False False False False  True  True  True  True]
[6 7 8 9] [1 2 3 4 5]
[False  True False  True False  True False  True False]
[2 4 6 8]
[4 5 6 7]
[ 0  6 12 18 24 30 36 42 48 54 60]


In [33]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
print (names)
print (names == 'Bob')
print (names[names == 'Bob'])
print (names[names != 'Bob'])
print (names[(names == 'Bob') | (names == 'Will')])  # don't use or but use |
names[names != 'Bob'] = 'Tom'   # assign based on a logical selection
print (names)
print (np.unique(names))        # getting all unique names

['Bob' 'Joe' 'Will' 'Bob']
[ True False False  True]
['Bob' 'Bob']
['Joe' 'Will']
['Bob' 'Will' 'Bob']
['Bob' 'Tom' 'Tom' 'Bob']
['Bob' 'Tom']


### **Vectorized Operations**

In [34]:
nums = np.arange(5)
print (nums)
print (nums * 5)         # multiply each element by 5
nums = np.sqrt(nums)     # square root of each element
print (nums)       
print (np.ceil(nums))    # finding ceiling of each element
print (np.floor(nums))   # finding floor of each element
nums = np.arange(5)
print (nums + np.arange(5)) # add element wise
print (np.isnan(nums))   # checks for NaN
nums = 2 * nums
print (nums)

[0 1 2 3 4]
[ 0  5 10 15 20]
[0.         1.         1.41421356 1.73205081 2.        ]
[0. 1. 2. 2. 2.]
[0. 1. 1. 1. 2.]
[0 2 4 6 8]
[False False False False False]
[0 2 4 6 8]


In [35]:
nums = np.arange(5)
print (nums)
print (np.maximum(nums, np.array([10, -2, 13, -4, 5]))) # compare element wise
print (np.minimum(nums, np.array([10, -2, 13, -4, 5])))

[0 1 2 3 4]
[10  1 13  3  5]
[ 0 -2  2 -4  4]


In [36]:
vect1 = np.random.randn(10)   # normalized random numbers, average and std near to 0 and 1 respectively
print (vect1, np.average(vect1), np.std(vect1))
vect2 = np.random.randn(10)
print (vect2, np.average(vect2), np.std(vect2))

[ 0.58370713 -0.79156106 -0.51549498  1.70654707  0.29855347  0.13242035
  1.55296924  1.2942879   0.74922702 -0.95039368] 0.4060262459460911 0.9030449060550332
[-1.17409796  0.54860724  0.0292252  -0.82123274 -0.92773899  0.0949012
  0.38572463 -0.43683824 -0.82717004  0.0777171 ] -0.3050902581468487 0.5764997682908649


In [37]:
vect1 = np.random.randn(10000)   # normalized random numbers, average and std near to 0 and 1 respectively
print (vect1, np.average(vect1), np.std(vect1))
vect2 = np.random.randn(10000)
print (vect2, np.average(vect2), np.std(vect2))

[-1.02077432  0.23048407 -1.24756172 ... -0.17557384 -0.44464391
  0.84365625] 0.0027417434257655587 1.010314153431256
[-2.15316457  0.69715276 -1.48518944 ... -1.5055282  -1.52594605
  0.3223855 ] -0.0005817511488698947 1.0036896727144393


In [43]:
vec1 = np.random.rand(10)   # random numbers ranging from 0 to 1
print (vec1)

[0.94667099 0.8073096  0.46856964 0.72797601 0.23348598 0.09605216
 0.89686116 0.34137415 0.04831693 0.6489428 ]


In [44]:
# math and stats
rnd = np.random.randn(4, 2)
print (rnd)
print (rnd.mean())
print (rnd.std())
print (rnd.argmin(), rnd.argmax())   # index of the minimum and maximum element
print (rnd.sum(axis = 0))   # sum of columns
print (rnd.sum(axis = 1))   # sum of rows

[[-0.06470675  0.57883746]
 [ 0.51648768  0.69731007]
 [-1.05076967 -1.03608142]
 [-0.10738135 -0.47394536]]
-0.11753116674104613
0.6514856679367429
4 3
[-0.70637009 -0.23387925]
[ 0.51413071  1.21379776 -2.0868511  -0.58132671]


In [52]:
# random numbers
np.random.seed(1001)            # set the seed value for the random number generation
nums = np.random.rand(2, 3)     # 2 x 3 matrix
print (nums)
nums = np.random.randn(10)      # random normals (mean with 0 and std with 1)
print (nums)
nums = np.random.randint(0, 2, 10)    # 10 randomly picked 0 or 1
print (nums)

[[0.30623218 0.26506357 0.19606006]
 [0.43052148 0.02311355 0.19578192]]
[-1.20658558 -0.64172681  1.30794563  1.84546043  0.82911495 -0.02329881
 -0.20856395 -0.91661975 -1.07474258 -0.08614349]
[0 0 1 1 1 0 0 0 1 0]


In [56]:
nums = np.random.rand(2, 3)     # 2 x 3 matrix
print (nums)

[[0.43428678 0.56856169 0.01962086]
 [0.36514669 0.46953891 0.24526653]]


In [57]:
a1 = np.array([[ 0,  0,  0],
               [10, 10, 10],
               [20, 20, 20],
               [30, 30, 30]])
print (a1, type(a1))
a2 = np.array([[0], [10], [20], [30]])
print (a2, type(a2))

b1 = np.array([[0, 1, 2],
               [0, 1, 2],
               [0, 1, 2],               
               [0, 1, 2]])
print (b1, type(b1))
b2 = np.array([0, 1, 2])
print (b2, type(b2))

result = a1 + b1
print (result)

result = a1 + b2
print (result)

result = a2 + b1
print (result)

result = a2 + b2
print (result)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] <class 'numpy.ndarray'>
[[ 0]
 [10]
 [20]
 [30]] <class 'numpy.ndarray'>
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]] <class 'numpy.ndarray'>
[0 1 2] <class 'numpy.ndarray'>
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
